### ISSUE TITLE
Cannot use RoslynCodeDomProvider on .NET 7

### ISSUE THREAD

**Issue by matteot** [aspnet/RoslynCodeDomProvider#160]
Hi, I'm trying to use your package from a console app (.NET 7) and I obtain the error shown below. On the other hand everything works correctly if I reference and run your package in .NET 4.8.  Is .NET7+ is a supported scenario ?  Best regards, Matteo

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CompilationUtil' threw an exception.
 ---> System.TypeLoadException: Could not load type 'System.Web.Configuration.WebConfigurationManager' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.AppSettings.EnsureSettingsLoaded()
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.AppSettings.get_RoslynCompilerLocation()
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CompilationUtil.GetProviderOptionsFor(String fileExt)
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CompilationUtil..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CompilationUtil.get_CSC2()
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider..ctor(IProviderOptions providerOptions)
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider..ctor()
```

**Comment by StephenMolloy** [comment]
Unfortunately not. This package was developed for .Net Framework (ASP.Net "Classic" scenarios specifically, although we have seen a number of folks using it in non-web applications) and does not support .Net Core. I'm not sure `System.CodeDom` directly supports dynamic compilation in .Net Core. But I do know this - despite having to double and triple-check the veracity of answers from various AI models - many of them are more eloquent than me.  So here's a little bit of copy/pasta for elucidation. But no, this provider is not for .Net Core.

---

## Summary & Recommendations
- **For Code Generation:**
  You can still build your code tree using System.CodeDom if you like its model for code transformation. But for dynamic compilation in .NET Core, the landscape is different.
- **For Dynamic Compilation:**
  The recommended approach is to use the Roslyn APIs directly. This method is better integrated, offers more control, and is actively maintained.
  To compile your generated source code, you’ll need to explicitly use the Roslyn APIs (from the Microsoft.CodeAnalysis.CSharp package). With Roslyn, you can create a SyntaxTree from your source code, set up a CSharpCompilation (providing necessary references, options, etc.) and then compile in memory (or to disk). This is effectively what modern tooling recommends—and it’s what new projects target.
- **Mixing Approaches:**
  If you have legacy systems that rely on CodeDom for code generation, you might continue using it for creating your source code strings. But rather than invoking a CodeDom provider for compilation, feed the generated source into a Roslyn compilation pipeline.

By embracing Roslyn directly (or via its scripting APIs), you align with the modern direction of .NET and gain access to a richer set of features—including better diagnostics, customizable compilation options, and more flexible runtime usage.

## Further Thoughts
Since you clearly have experience with both technical intricacies and dynamically generating code, you might explore additional enhancements such as:

- **Custom Syntax Trees:** Experiment with generating and transforming Roslyn syntax trees directly rather than going through CodeDom as an intermediary.
- **Debugging Dynamics:** Take advantage of Roslyn’s rich diagnostic capabilities to better debug dynamically generated code.
- **Security and Sandbox Considerations:** When compiling and executing dynamic code in .NET Core, the assembly load context and security restrictions can differ from .NET Framework; it’s worth reviewing those for your use case.

This modern approach not only complements a seasoned developer’s skill set but also offers opportunities to delve deeper into the workings of the C# compiler itself—a fascinating realm of modern .NET development.
